### ISSUE TITLE
Adding background color to table rows

### ISSUE THREAD

**Issue by dhimmel** [data2health/contributorship#13]
Thanks @samteplitzky for all the work transferring the manuscript to this repository. I'll respond here to your message:

> I'm in the process of transferring the contributor commentary to manubot. I think I know the answer to this, but is there a way to add color to table cells/rows to replicate how they are represented in the google doc? I'm assuming that's a limitation of markdown, but just wanted to check.

For reference, here's what the google doc looks like:

![image](https://user-images.githubusercontent.com/1117703/78936619-f00ae280-7a7c-11ea-8d24-90cb51d13e6c.png)

Will follow up with a solution!

**Comment by dhimmel** [comment]
From the [delete-me](https://github.com/manubot/rootstock/raw/7c0f9c30fe03a6e264e19d08f2337266a4ea3e3e/content/02.delete-me.md)

```
Available background colors for text, images, code, banners, etc:  

`white`{.white}
`lightgrey`{.lightgrey}
`grey`{.grey}
`darkgrey`{.darkgrey}
`black`{.black}
`lightred`{.lightred}
`lightyellow`{.lightyellow}
`lightgreen`{.lightgreen}
`lightblue`{.lightblue}
`lightpurple`{.lightpurple}
`red`{.red}
`orange`{.orange}
`yellow`{.yellow}
`green`{.green}
`blue`{.blue}
`purple`{.purple}
```

See the colors at https://manubot.github.io/rootstock/v/7c0f9c30fe03a6e264e19d08f2337266a4ea3e3e/#special:

![image](https://user-images.githubusercontent.com/1117703/78937101-dfa73780-7a7d-11ea-8c0f-e51ecc3e0524.png)

**Comment by dhimmel** [comment]
For an individual cell, you could do `[text for my cell]{.green}`.

This would probably get annoying to do in every cell, but perhaps you could do it for just one column?

Note you also can do it in the caption, if you'd like to add color to category mentions.

**Comment by samteplitzky** [comment]
Thanks! I'll give it a try.
