### ISSUE TITLE
Setting up GitHub actions to build the manuscript

### ISSUE THREAD

**Issue by dhimmel** [data2health/contributorship#3]
We have a brand new workflow for GitHub actions at https://github.com/manubot/rootstock/pull/297, which I'd like to use to build the manuscript (rather than the traditional Travis CI).

@nicolevasilevsky I don't think I have the credentials I need to access the repository settings. Are you able to elevate my credentials for this repo?

**Comment by nicolevasilevsky** [comment]
@dhimmel let me know if that worked, I changed your status to maintain

**Comment by dhimmel** [comment]
> let me know if that worked, I changed your status to maintain

I need more hehe! The "Admin" level until I add the necessary keys.

**Comment by nicolevasilevsky** [comment]
you are now admin!

**Comment by dhimmel** [comment]
> you are now admin!

Got it and set up the deployment keys. So now the manuscript gets published to https://data2health.github.io/contributorship/

**Comment by nicolevasilevsky** [comment]
very cool!
